Revert "fixed: Don't do GetLength() off-thread is it may be (b)locked by a pending read() (fixes #16046)" fixes:
 xbmc/filesystem/filesystem.a(FileCache.o): In function
`std::__atomic_base<long long>::load(std::memory_order) const':
|
/home/marko/git/openpli-oe-core/build/tmp/sysroots/vusolose/usr/include/c++/4.9.1/bits/atomic_base.h:500:
undefined reference to `__atomic_load_8'
| xbmc/filesystem/filesystem.a(FileCache.o): In function
`std::__atomic_base<long long>::store(long long, std::memory_order)':
|
/home/marko/git/openpli-oe-core/build/tmp/sysroots/vusolose/usr/include/c++/4.9.1/bits/atomic_base.h:478:
undefined reference to `__atomic_store_8'
| xbmc/filesystem/filesystem.a(FileCache.o): In function
`std::__atomic_base<long long>::load(std::memory_order) const':
|
/home/marko/git/openpli-oe-core/build/tmp/sysroots/vusolose/usr/include/c++/4.9.1/bits/atomic_base.h:500:
undefined reference to `__atomic_load_8'
|
/home/marko/git/openpli-oe-core/build/tmp/sysroots/vusolose/usr/include/c++/4.9.1/bits/atomic_base.h:500:
undefined reference to `__atomic_load_8'
|
/home/marko/git/openpli-oe-core/build/tmp/sysroots/vusolose/usr/include/c++/4.9.1/bits/atomic_base.h:500:
undefined reference to `__atomic_load_8'
| xbmc/filesystem/filesystem.a(FileCache.o): In function
`std::__atomic_base<long long>::store(long long, std::memory_order)':
|
/home/marko/git/openpli-oe-core/build/tmp/sysroots/vusolose/usr/include/c++/4.9.1/bits/atomic_base.h:478:
undefined reference to `__atomic_store_8

It's probably gcc issue:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65147

We should revert it back in gcc5.1+

This reverts commit 593f4aa0ba7e572394111a856ec9b54ed7a8351b.