[basedonvu] turn off audio engine
alsa is currently not working correctly, we are getting messages like this:

ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover
ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover

and sound is choppy.

Probably wrongly set hwparams for alsa, since playback
works nicely with aplay?